name: t3-clone-base
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
description: A minimal Google Cloud TypeScript Pulumi program
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-typescript
